In [1]:
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import TfidfTransformer

/home/aryansharma/Desktop/Aryan Pendrive Data/Support-Integrity-Auditor/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
print("="*50)
print("Loading Sentence Transformer...")
print("="*50)
encoder = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

==================================================
Loading Sentence Transformer...
==================================================

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6106.37it/s]

In [3]:
def encoding(row):
    return encoder.encode(f"{row['Ticket_Subject']} | {row['Ticket_Description']} | {row['Issue_Category']} | {row['Ticket_Channel']} | {row['Submission_Date']} | {row['Resolution_Time_Hours']} | {row['Satisfaction_Score']}")

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("../dataset/preprocessed_data.csv")

In [6]:
results = []
for idx,row in df.iterrows():
    if(idx+1)%100==0:
        print(f"{idx+1} Completed")
    results.append(encoding(row))

100 Completed
200 Completed
300 Completed
400 Completed
500 Completed
600 Completed
700 Completed
800 Completed
900 Completed
1000 Completed
1100 Completed
1200 Completed
1300 Completed
1400 Completed
1500 Completed
1600 Completed
1700 Completed
1800 Completed
1900 Completed
2000 Completed
2100 Completed
2200 Completed
2300 Completed
2400 Completed
2500 Completed
2600 Completed
2700 Completed
2800 Completed
2900 Completed
3000 Completed
3100 Completed
3200 Completed
3300 Completed
3400 Completed
3500 Completed
3600 Completed
3700 Completed
3800 Completed
3900 Completed
4000 Completed
4100 Completed
4200 Completed
4300 Completed
4400 Completed
4500 Completed
4600 Completed
4700 Completed
4800 Completed
4900 Completed
5000 Completed
5100 Completed
5200 Completed
5300 Completed
5400 Completed
5500 Completed
5600 Completed
5700 Completed
5800 Completed
5900 Completed
6000 Completed
6100 Completed
6200 Completed
6300 Completed
6400 Completed
6500 Completed
6600 Completed
6700 Completed
6800 Completed
6900 Completed
7000 Completed
7100 Completed
7200 Completed
7300 Completed
7400 Completed
7500 Completed
7600 Completed
7700 Completed
7800 Completed
7900 Completed
8000 Completed
8100 Completed
8200 Completed
8300 Completed
8400 Completed
8500 Completed
8600 Completed
8700 Completed
8800 Completed
8900 Completed
9000 Completed
9100 Completed
9200 Completed
9300 Completed
9400 Completed
9500 Completed
9600 Completed
9700 Completed
9800 Completed
9900 Completed
10000 Completed
10100 Completed
10200 Completed
10300 Completed
10400 Completed
10500 Completed
10600 Completed
10700 Completed
10800 Completed
10900 Completed
11000 Completed
11100 Completed
11200 Completed
11300 Completed
11400 Completed
11500 Completed
11600 Completed
11700 Completed
11800 Completed
11900 Completed
12000 Completed
12100 Completed
12200 Completed
12300 Completed
12400 Completed
12500 Completed
12600 Completed
12700 Completed
12800 Completed
12900 Completed
13000 Completed
13100 Completed
13200 Completed
13300 Completed
13400 Completed
13500 Completed
13600 Completed
13700 Completed
13800 Completed
13900 Completed
14000 Completed
14100 Completed
14200 Completed
14300 Completed
14400 Completed
14500 Completed
14600 Completed
14700 Completed
14800 Completed
14900 Completed
15000 Completed
15100 Completed
15200 Completed
15300 Completed
15400 Completed
15500 Completed
15600 Completed
15700 Completed
15800 Completed
15900 Completed
16000 Completed
16100 Completed
16200 Completed
16300 Completed
16400 Completed
16500 Completed
16600 Completed
16700 Completed
16800 Completed
16900 Completed
17000 Completed
17100 Completed
17200 Completed
17300 Completed
17400 Completed
17500 Completed
17600 Completed
17700 Completed
17800 Completed
17900 Completed
18000 Completed
18100 Completed
18200 Completed
18300 Completed
18400 Completed
18500 Completed
18600 Completed
18700 Completed
18800 Completed
18900 Completed
19000 Completed
19100 Completed
19200 Completed
19300 Completed
19400 Completed
19500 Completed
19600 Completed
19700 Completed
19800 Completed
19900 Completed
20000 Completed

In [7]:
encod_df = pd.DataFrame(results,index=df.Ticket_ID)
encod_df

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
Ticket_ID,,,,,,,,,,,,,,,,,,,,,
TKT-100000,0.002571,-0.019472,0.070719,0.053733,-0.044791,-0.007131,-0.030423,-0.006582,-0.078199,-0.034101,...,-0.052496,0.069139,0.074753,-0.003721,0.040896,0.044177,-0.025906,0.006920,-0.072082,-0.015856
TKT-100001,0.011041,-0.061306,0.033112,-0.008299,-0.069371,0.016763,-0.053555,-0.015784,-0.070515,-0.029208,...,0.035491,-0.006290,0.023089,0.012584,0.058920,-0.032232,0.035037,0.036454,-0.063948,-0.009814
TKT-100002,-0.002739,-0.022724,0.049826,-0.016715,0.033351,0.058095,-0.008124,0.016174,-0.116878,-0.003589,...,-0.086589,-0.055474,-0.000981,0.052203,-0.050234,0.052765,0.070131,0.017189,0.011927,0.050742
TKT-100003,-0.004949,0.006126,0.016192,-0.086378,0.032637,-0.036519,-0.010225,0.016238,-0.043331,-0.012600,...,-0.041719,-0.025982,0.003898,0.051001,-0.060152,-0.021808,0.023480,0.044091,0.009545,-0.028579
TKT-100004,-0.061894,-0.006993,0.062786,0.019193,-0.035246,-0.008102,-0.038648,-0.011365,-0.049389,0.074313,...,-0.004700,-0.042259,0.037683,-0.049518,-0.057396,-0.027763,0.115490,-0.009413,0.004474,0.009316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TKT-119995,0.055097,-0.052753,0.056174,-0.057679,-0.040987,-0.022366,0.003055,0.065018,-0.119041,0.019488,...,0.025544,-0.002706,0.035714,0.006888,0.062341,-0.039623,0.102574,0.021393,-0.011440,0.019101
TKT-119996,-0.092078,-0.006094,0.019352,-0.004132,0.075780,-0.047996,0.145494,-0.047185,0.043007,0.011004,...,-0.038050,-0.034390,0.031794,-0.016751,0.018151,0.008170,0.096519,-0.043935,-0.001581,0.058341
TKT-119997,-0.052657,-0.035479,0.066586,-0.005769,0.122613,-0.010897,-0.041313,-0.055158,-0.075286,0.014604,...,-0.091286,-0.061807,0.128629,-0.022351,0.022152,0.045680,0.047917,-0.048787,-0.049576,-0.022244
TKT-119998,-0.054596,0.072214,-0.016701,-0.024117,0.007224,-0.039848,-0.027102,-0.058875,-0.014294,0.059226,...,-0.005937,-0.048469,0.025784,-0.002742,-0.010334,0.054352,0.142249,-0.066403,0.048843,0.007754
TKT-119999,-0.085586,-0.029770,0.029615,-0.045036,0.007083,0.006638,-0.150096,-0.004848,-0.188268,-0.000749,...,0.061462,0.124733,0.028211,-0.037062,-0.006422,-0.037432,0.111906,-0.010461,-0.066041,0.102783

In [8]:
from sklearn.ensemble import RandomForestClassifier

In [9]:
df = df.set_index("Ticket_ID")

In [10]:
encod_df["Target"] = df["Is_Mismatch"]

In [11]:
encod_df

,0,1,2,3,4,5,6,7,8,9,...,375,376,377,378,379,380,381,382,383,Target
Ticket_ID,,,,,,,,,,,,,,,,,,,,,
TKT-100000,0.002571,-0.019472,0.070719,0.053733,-0.044791,-0.007131,-0.030423,-0.006582,-0.078199,-0.034101,...,0.069139,0.074753,-0.003721,0.040896,0.044177,-0.025906,0.006920,-0.072082,-0.015856,1
TKT-100001,0.011041,-0.061306,0.033112,-0.008299,-0.069371,0.016763,-0.053555,-0.015784,-0.070515,-0.029208,...,-0.006290,0.023089,0.012584,0.058920,-0.032232,0.035037,0.036454,-0.063948,-0.009814,1
TKT-100002,-0.002739,-0.022724,0.049826,-0.016715,0.033351,0.058095,-0.008124,0.016174,-0.116878,-0.003589,...,-0.055474,-0.000981,0.052203,-0.050234,0.052765,0.070131,0.017189,0.011927,0.050742,0
TKT-100003,-0.004949,0.006126,0.016192,-0.086378,0.032637,-0.036519,-0.010225,0.016238,-0.043331,-0.012600,...,-0.025982,0.003898,0.051001,-0.060152,-0.021808,0.023480,0.044091,0.009545,-0.028579,1
TKT-100004,-0.061894,-0.006993,0.062786,0.019193,-0.035246,-0.008102,-0.038648,-0.011365,-0.049389,0.074313,...,-0.042259,0.037683,-0.049518,-0.057396,-0.027763,0.115490,-0.009413,0.004474,0.009316,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TKT-119995,0.055097,-0.052753,0.056174,-0.057679,-0.040987,-0.022366,0.003055,0.065018,-0.119041,0.019488,...,-0.002706,0.035714,0.006888,0.062341,-0.039623,0.102574,0.021393,-0.011440,0.019101,1
TKT-119996,-0.092078,-0.006094,0.019352,-0.004132,0.075780,-0.047996,0.145494,-0.047185,0.043007,0.011004,...,-0.034390,0.031794,-0.016751,0.018151,0.008170,0.096519,-0.043935,-0.001581,0.058341,0
TKT-119997,-0.052657,-0.035479,0.066586,-0.005769,0.122613,-0.010897,-0.041313,-0.055158,-0.075286,0.014604,...,-0.061807,0.128629,-0.022351,0.022152,0.045680,0.047917,-0.048787,-0.049576,-0.022244,1
TKT-119998,-0.054596,0.072214,-0.016701,-0.024117,0.007224,-0.039848,-0.027102,-0.058875,-0.014294,0.059226,...,-0.048469,0.025784,-0.002742,-0.010334,0.054352,0.142249,-0.066403,0.048843,0.007754,0
TKT-119999,-0.085586,-0.029770,0.029615,-0.045036,0.007083,0.006638,-0.150096,-0.004848,-0.188268,-0.000749,...,0.124733,0.028211,-0.037062,-0.006422,-0.037432,0.111906,-0.010461,-0.066041,0.102783,0

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_Train,X_test,y_train,y_test = train_test_split(encod_df.drop(columns=["Target"]), encod_df["Target"], test_size=0.2 ,stratify=encod_df["Target"])

In [14]:
X_Train.shape

(16000, 384)

In [15]:
model = RandomForestClassifier()
model.fit(X_Train,y_train)

RandomForestClassifier()

In [16]:
from sklearn.metrics import classification_report

In [17]:
y_pred = model.predict(X_test)
report = classification_report(y_test,y_pred)

print(report)

              precision    recall  f1-score   support

           0       0.53      0.33      0.40      1384
           1       0.70      0.85      0.77      2616

    accuracy                           0.67      4000
   macro avg       0.62      0.59      0.59      4000
weighted avg       0.65      0.67      0.64      4000

In [18]:
from xgboost import XGBClassifier

In [19]:
model = XGBClassifier()
model.fit(X_Train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [20]:
y_pred = model.predict(X_test)
report = classification_report(y_test,y_pred)

print(report)

              precision    recall  f1-score   support

           0       0.48      0.36      0.41      1384
           1       0.70      0.80      0.75      2616

    accuracy                           0.65      4000
   macro avg       0.59      0.58      0.58      4000
weighted avg       0.63      0.65      0.63      4000

In [21]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

In [22]:
model.fit(X_Train,y_train)

LogisticRegression()

In [23]:
y_pred = model.predict(X_test)
report = classification_report(y_test,y_pred)

print(report)

              precision    recall  f1-score   support

           0       0.52      0.29      0.38      1384
           1       0.70      0.86      0.77      2616

    accuracy                           0.66      4000
   macro avg       0.61      0.58      0.57      4000
weighted avg       0.64      0.66      0.63      4000

In [24]:
encod_df["Issue_Category"] = df["Issue_Category"]
encod_df["Ticket_Channel"] = df["Ticket_Channel"]
encod_df["Resolution_Time_Hours"] = df["Resolution_Time_Hours"]

In [25]:
encod_df = pd.get_dummies(encod_df,columns=["Issue_Category","Ticket_Channel"], drop_first=True, dtype=int)

In [26]:
X_Train,X_test,y_train,y_test = train_test_split(encod_df.drop(columns=["Target"]), encod_df["Target"], test_size=0.2 ,stratify=encod_df["Target"])

In [27]:
X_Train.columns = X_Train.columns.astype(str)

In [28]:
model = XGBClassifier()
model.fit(X_Train,y_train)
y_pred = model.predict(X_test)
report = classification_report(y_test,y_pred)

print(report)

              precision    recall  f1-score   support

           0       0.50      0.38      0.43      1384
           1       0.71      0.80      0.75      2616

    accuracy                           0.65      4000
   macro avg       0.60      0.59      0.59      4000
weighted avg       0.63      0.65      0.64      4000

In [29]:
X_Train.columns = X_Train.columns.astype(str)
X_test.columns = X_test.columns.astype(str)

In [30]:
model = RandomForestClassifier()
model.fit(X_Train,y_train)
y_pred = model.predict(X_test)
report = classification_report(y_test,y_pred)

print(report)

              precision    recall  f1-score   support

           0       0.51      0.33      0.40      1384
           1       0.70      0.83      0.76      2616

    accuracy                           0.66      4000
   macro avg       0.60      0.58      0.58      4000
weighted avg       0.63      0.66      0.64      4000

In [31]:
model = LogisticRegression()
model.fit(X_Train,y_train)
y_pred = model.predict(X_test)
report = classification_report(y_test,y_pred)

print(report)

              precision    recall  f1-score   support

           0       0.54      0.29      0.38      1384
           1       0.70      0.87      0.77      2616

    accuracy                           0.67      4000
   macro avg       0.62      0.58      0.58      4000
weighted avg       0.64      0.67      0.64      4000

/home/aryansharma/Desktop/Aryan Pendrive Data/Support-Integrity-Auditor/.venv/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [32]:
from lightgbm import LGBMClassifier

In [33]:
model = LGBMClassifier()
model.fit(X_Train,y_train)
y_pred = model.predict(X_test)
report = classification_report(y_test,y_pred)

print(report)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 10466, number of negative: 5534
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.020973 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 98053
[LightGBM] [Info] Number of data points in the train set: 16000, number of used features: 391
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.654125 -> initscore=0.637221
[LightGBM] [Info] Start training from score 0.637221
              precision    recall  f1-score   support

           0       0.52      0.36      0.43      1384
           1       0.71      0.82      0.76      2616

    accuracy                           0.67      4000
   macro avg       0.62      0.59      0.60      4000
weighted avg       0.65      0.67      0.65      4000

In [34]:
df.columns

Index(['Customer_Name', 'Customer_Email', 'Ticket_Subject',
       'Ticket_Description', 'Issue_Category', 'Priority_Level',
       'Ticket_Channel', 'Submission_Date', 'Resolution_Time_Hours',
       'Assigned_Agent', 'Satisfaction_Score', 'low_score', 'medium_score',
       'high_score', 'critical_score', 'Final_severity_label', 'Is_Mismatch'],
      dtype='str')